name: xc8
description: Find8
publish_to: none
version: 1.0.0+1

environment:
  sdk: '^3.0.5'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.0
  bip340: ^0.0.4
  drag_and_drop_lists: ^0.3.3
  cupertino_icons: ^1.0.2
  http: ^1.0.0
  crypto: ^3.0.2
  fractal_flutter:
    path: ../../pub/fractal_flutter
  frac:
    path: ../../pub/frac
  data8:
    path: ../data8
  regexpattern: ^2.1.0
  just_the_tooltip: ^0.0.12
  pasteboard: ^0.2.0
  drift: ^2.9.0
  qr_flutter: ^4.0.0
  webview_flutter: ^4.0.6
  flutter_provider: ^2.1.0
  provider: ^6.0.5
  url_launcher: ^6.1.10
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  velocity_x: ^4.1.0
  yaml_writer: ^1.0.3
  two8: 
    path: ../two8
  sqlite3_flutter_libs:
  json_annotation:
  file_picker: ^5.3.2
  path_provider: ^2.0.15
  timeago_flutter: ^3.5.0
  accordion: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700